// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// Wire function
func InjectDependencies() *AppDependencies {
	// db := initialize.LoadDbPostgres()
	// client := initialize.LoadRedis()
	appDependencies := &AppDependencies{
		DB:    db,
		Redis: client,
	}
	return appDependencies
}

// wire.go:

type AppDependencies struct {
	DB    *gorm.DB
	Redis *redis.Client
}
