// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: product.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductSimpleService_CreateOrUpdate_FullMethodName = "/product.ProductSimpleService/CreateOrUpdate"
)

// ProductSimpleServiceClient is the client API for ProductSimpleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductSimpleServiceClient interface {
	CreateOrUpdate(ctx context.Context, in *ProductSimpleDTO, opts ...grpc.CallOption) (*ProductSimpleResponse, error)
}

type productSimpleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductSimpleServiceClient(cc grpc.ClientConnInterface) ProductSimpleServiceClient {
	return &productSimpleServiceClient{cc}
}

func (c *productSimpleServiceClient) CreateOrUpdate(ctx context.Context, in *ProductSimpleDTO, opts ...grpc.CallOption) (*ProductSimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductSimpleResponse)
	err := c.cc.Invoke(ctx, ProductSimpleService_CreateOrUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductSimpleServiceServer is the server API for ProductSimpleService service.
// All implementations must embed UnimplementedProductSimpleServiceServer
// for forward compatibility.
type ProductSimpleServiceServer interface {
	CreateOrUpdate(context.Context, *ProductSimpleDTO) (*ProductSimpleResponse, error)
	mustEmbedUnimplementedProductSimpleServiceServer()
}

// UnimplementedProductSimpleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductSimpleServiceServer struct{}

func (UnimplementedProductSimpleServiceServer) CreateOrUpdate(context.Context, *ProductSimpleDTO) (*ProductSimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdate not implemented")
}
func (UnimplementedProductSimpleServiceServer) mustEmbedUnimplementedProductSimpleServiceServer() {}
func (UnimplementedProductSimpleServiceServer) testEmbeddedByValue()                              {}

// UnsafeProductSimpleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductSimpleServiceServer will
// result in compilation errors.
type UnsafeProductSimpleServiceServer interface {
	mustEmbedUnimplementedProductSimpleServiceServer()
}

func RegisterProductSimpleServiceServer(s grpc.ServiceRegistrar, srv ProductSimpleServiceServer) {
	// If the following call panics, it indicates UnimplementedProductSimpleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductSimpleService_ServiceDesc, srv)
}

func _ProductSimpleService_CreateOrUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductSimpleDTO)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductSimpleServiceServer).CreateOrUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductSimpleService_CreateOrUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductSimpleServiceServer).CreateOrUpdate(ctx, req.(*ProductSimpleDTO))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductSimpleService_ServiceDesc is the grpc.ServiceDesc for ProductSimpleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductSimpleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.ProductSimpleService",
	HandlerType: (*ProductSimpleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrUpdate",
			Handler:    _ProductSimpleService_CreateOrUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
